#/**************************************************************************
# *                                                                        *
# *         Copyright (c) 2005 by Sunplus Technology Co., Ltd.             *
# *                                                                        *
# *  This software is copyrighted by and is the property of Sunplus        *
# *  Technology Co., Ltd. All rights are reserved by Sunplus Technology    *
# *  Co., Ltd. This software may only be used in accordance with the       *
# *  corresponding license agreement. Any unauthorized use, duplication,   *
# *  distribution, or disclosure of this software is expressly forbidden.  *
# *                                                                        *
# *  This Copyright notice MUST not be removed or modified without prior   *
# *  written consent of Sunplus Technology Co., Ltd.                       *
# *                                                                        *
# *  Sunplus Technology Co., Ltd. reserves the right to modify this        *
# *  software without notice.                                              *
# *                                                                        *
# *  Sunplus Technology Co., Ltd.                                          *
# *  19, Innovation First Road, Science-Based Industrial Park,             *
# *  Hsin-Chu, Taiwan, R.O.C.                                              *
# *                                                                        *
# *  Author: Jason                                                         *
# *                                                                        *
# *  Reviewer:                                                             *
# *                                                                        *
# **************************************************************************/

#---------------------------------------------------------------------------
# Target definition (User)
GOAL  = simple

# Shared objects
C_SRC =
CPP_SRC =

ROOT_DIR	+=../..
TEST_DIR	+= $(ROOT_DIR)/test/simple
SOURCE_DIR	+= $(ROOT_DIR)/src
LIB_SRC		+= $(ROOT_DIR)/lib/libgsl.a

include $(ROOT_DIR)/make.include
include $(ROOT_DIR)/Makefile.in

