#!/bin/sh


# mpatrol
# A library for controlling and tracing dynamic memory allocations.
# Copyright (C) 1997-2002 Graeme S. Roy <graeme.roy@analog.com>
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Library General Public
# License as published by the Free Software Foundation; either
# version 2 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Library General Public License for more details.
#
# You should have received a copy of the GNU Library General Public
# License along with this library; if not, write to the Free
# Software Foundation, Inc., 59 Temple Place, Suite 330, Boston,
# MA 02111-1307, USA.


# UNIX shell script to build an RPM package file


# $Id: build,v 1.34 2002/01/08 20:22:08 graeme Exp $


arch=i386
version=1.4.8
base=/usr


# Build the binary and source package files.  This assumes that the source
# archive exists in /usr/src/redhat/SOURCES.  If this is impossible (because
# you are not the superuser) then you can override the use of /usr as the
# base directory by placing a file called .rpmmacros in your home directory
# and adding a new definition of %_usr within it.

rpm -ba --clean mpatrol.spec
cp $base/src/redhat/RPMS/$arch/mpatrol-$version-1.$arch.rpm .
rm -f $base/src/redhat/RPMS/$arch/mpatrol-$version-1.$arch.rpm
cp $base/src/redhat/SRPMS/mpatrol-$version-1.src.rpm .
rm -f $base/src/redhat/SRPMS/mpatrol-$version-1.src.rpm
