#!/bin/sh


# mpatrol
# A library for controlling and tracing dynamic memory allocations.
# Copyright (C) 1997-2008 Graeme S. Roy <graemeroy@users.sourceforge.net>
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser
# General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


# UNIX shell script to build an RPM package file


# $Id$


arch=i386
version=1.5.1
base=/usr


# Build the binary and source package files.  This assumes that the source
# archive exists in /usr/src/redhat/SOURCES.  If this is impossible (because
# you are not the superuser) then you can override the use of /usr as the
# base directory by placing a file called .rpmmacros in your home directory
# and adding a new definition of %_usr within it.

rpm -ba --clean mpatrol.spec
cp $base/src/redhat/RPMS/$arch/mpatrol-$version-1.$arch.rpm .
rm -f $base/src/redhat/RPMS/$arch/mpatrol-$version-1.$arch.rpm
cp $base/src/redhat/SRPMS/mpatrol-$version-1.src.rpm .
rm -f $base/src/redhat/SRPMS/mpatrol-$version-1.src.rpm
