#!/bin/sh


# mpatrol
# A library for controlling and tracing dynamic memory allocations.
# Copyright (C) 1997-2002 Graeme S. Roy <graeme.roy@analog.com>
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Library General Public
# License as published by the Free Software Foundation; either
# version 2 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Library General Public License for more details.
#
# You should have received a copy of the GNU Library General Public
# License along with this library; if not, write to the Free
# Software Foundation, Inc., 59 Temple Place, Suite 330, Boston,
# MA 02111-1307, USA.


# UNIX shell script to remove the directory structure that is required by
# GNU autoconf, automake and libtool.


# $Id: cleanup,v 1.12 2002/01/08 20:18:08 graeme Exp $


rm -f README AUTHORS THANKS COPYING COPYING.LIB NEWS ChangeLog
rm -f INSTALL install-sh missing mkinstalldirs
rm -f config.guess config.sub ltconfig ltmain.sh
rm -f aclocal.m4 acconfig.h configure.in configure
rm -f configure.h.in stamp-h.in Makefile.am Makefile.in
rm -rf bin doc extra man src tsrc tools
