#!/bin/sh


# mpatrol
# A library for controlling and tracing dynamic memory allocations.
# Copyright (C) 1997-2008 Graeme S. Roy <graemeroy@users.sourceforge.net>
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser
# General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


# UNIX shell script to remove the directory structure that is required by
# GNU autoconf, automake and libtool.


# $Id$


rm -f README AUTHORS THANKS COPYING COPYING.LESSER NEWS ChangeLog
rm -f INSTALL depcomp install-sh missing mkinstalldirs
rm -f config.guess config.sub ltconfig ltmain.sh
rm -f aclocal.m4 acconfig.h configure.in configure
rm -f configure.h.in stamp-h.in Makefile.am Makefile.in
rm -rf bin doc extra man src tsrc tools
