/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNIFoo */

#ifndef _Included_JNIFoo
#define _Included_JNIFoo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNIFoo
 * Method:    nativeFoo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_JNIFoo_nativeFoo
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
