FILES = asynctest nbtest setconsole setlevel heartbeat mapper wmapper \
	inp outp datasize dataalign load50 netifdebug netifconfig mapcmp

INCLUDEDIR = /usr/include
CFLAGS = -O2 -fomit-frame-pointer -Wall -I$(INCLUDEDIR)

all: $(FILES)

clean:
	rm -f $(FILES) *~ core

