#/**************************************************************************
# *                                                                        *
# *         Copyright (c) 2005 by Sunplus Technology Co., Ltd.             *
# *                                                                        *
# *  This software is copyrighted by and is the property of Sunplus        *
# *  Technology Co., Ltd. All rights are reserved by Sunplus Technology    *
# *  Co., Ltd. This software may only be used in accordance with the       *
# *  corresponding license agreement. Any unauthorized use, duplication,   *
# *  distribution, or disclosure of this software is expressly forbidden.  *
# *                                                                        *
# *  This Copyright notice MUST not be removed or modified without prior   *
# *  written consent of Sunplus Technology Co., Ltd.                       *
# *                                                                        *
# *  Sunplus Technology Co., Ltd. reserves the right to modify this        *
# *  software without notice.                                              *
# *                                                                        *
# *  Sunplus Technology Co., Ltd.                                          *
# *  19, Innovation First Road, Science-Based Industrial Park,             *
# *  Hsin-Chu, Taiwan, R.O.C.                                              *
# *                                                                        *
# *  Author: Jason                                                         *
# *                                                                        *
# *  Reviewer:                                                             *
# *                                                                        *
# **************************************************************************/

#---------------------------------------------------------------------------
# Target definition (User)
GOAL  += cond0 cond1
GOAL  += posix task0 task1 task2 task3 task4 task5 taskx
GOAL  += timer0 timer1 timer2

#---------------------------------------------------------------------------
# Source section (User)
#---------------------------------------------------------------------------
ROOT_DIR = ../..

SOURCE_DIR	+=$(ROOT_DIR)/src
TEST_DIR	+=$(ROOT_DIR)/test/th-tm

include $(ROOT_DIR)/make.include
include $(ROOT_DIR)/Makefile.in

