TARGET = bin2hexheader hexheader2bin

all: $(TARGET)
	@echo "compile $(TARGET) done"

bin2hexheader:
	gcc -o bin2hexheader bin2hexheader.c 

hexheader2bin:
	gcc -o hexheader2bin hexheader2bin.c

clean:
	rm $(TARGET) 
